# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'

env:
  VERSION: ${{ github.ref_name }}
  FONT_ARCHIVE_NAME: SF-Mono-Nerd-Font-${{ github.ref_name }}.zip
  FONT_ARCHIVE_CHECKSUM_FILE_NAME: SF-Mono-Nerd-Font-${{ github.ref_name }}-SHA256SUM.txt

jobs:

  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract fonts
        run: ./extract-fonts.sh ./source

      - name: Checkout NerdFonts
        uses: actions/checkout@v4
        with:
          repository: 'ryanoasis/nerd-fonts'
          ref: refs/tags/v3.1.1
          fetch-depth: 1
          path: nerdfonts

      - name: Install FontForge
        run: brew install fontforge

      - name: Patch fonts
        run: for f in ./source/*.otf; do [ -f "$f" ] && ./nerdfonts/font-patcher -out /fonts --complete "$f"; done
      
      - name: Package fonts
        run: zip -rj ${{ env.FONT_ARCHIVE_NAME }} ./fonts # -j adds entries to the root of the archive.

      - name: Compute hash
        run: shasum -a 256 ${{ env.FONT_ARCHIVE_NAME }} > ${{ env.FONT_ARCHIVE_CHECKSUM_FILE_NAME }}
          
      # The create-release action created by GitHub is no longer maintained: https://github.com/actions/create-release.
      # At the time of writing, ncipollo/release-action is listed on the repo as one of the recommended alternatives.
      - uses: ncipollo/release-action@v1
        name: Create release
        with:
          tag: ${{ env.version }}
          artifacts: "${{ env.FONT_ARCHIVE_NAME }},${{ env.FONT_ARCHIVE_CHECKSUM_FILE_NAME }}"
